version: '3.9'

services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata_rebase_labs:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "bundle exec sidekiq -r ./app/jobs/application_job.rb"
    volumes:
      - .:/rebase_labs

  rebase-labs:
    depends_on:
      - postgres
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "bundle exec puma"
    volumes:
      - .:/rebase_labs
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

volumes:
  pgdata_rebase_labs:
  rubygems: